"""add_all_tables_phase2

Revision ID: 67c6772b693e
Revises: 182838c933d7
Create Date: 2026-03-08 16:08:39.810891
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '67c6772b693e'
down_revision: Union[str, None] = '182838c933d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_packages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('credit_amount', sa.Integer(), nullable=False),
    sa.Column('bonus_credit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('badge', sa.String(length=50), nullable=True),
    sa.Column('min_tier', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membership_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('price_monthly', sa.Numeric(precision=12, scale=0), server_default='0', nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=12, scale=0), server_default='0', nullable=False),
    sa.Column('priority_level', sa.Integer(), server_default='1', nullable=False),
    sa.Column('daily_credit_limit', sa.Integer(), server_default='50', nullable=False),
    sa.Column('max_jobs', sa.Integer(), server_default='3', nullable=False),
    sa.Column('max_urls_per_job', sa.Integer(), server_default='10', nullable=False),
    sa.Column('max_clients', sa.Integer(), server_default='1', nullable=False),
    sa.Column('credit_earn_multiplier', sa.Numeric(precision=3, scale=1), server_default='1.0', nullable=False),
    sa.Column('allow_keyword_seo', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_backlink', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_social_media', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_internal_click', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_proxy', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_scheduling', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_priority_boost', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('allow_detailed_report', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payment_channels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('fee_percent', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('min_amount', sa.Numeric(precision=12, scale=0), server_default='10000', nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=12, scale=0), server_default='10000000', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promotions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_purchase', sa.Numeric(precision=12, scale=0), nullable=True),
    sa.Column('min_tier', sa.String(length=20), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('max_uses_per_user', sa.Integer(), server_default='1', nullable=False),
    sa.Column('current_uses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('proxies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('protocol', sa.String(length=10), server_default='http', nullable=False),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), server_default='100.0', nullable=False),
    sa.Column('avg_response_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.String(length=255), nullable=True),
    sa.Column('os_info', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('is_online', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('disconnected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tasks_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('tasks_failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('credits_earned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('client_version', sa.String(length=20), nullable=True),
    sa.Column('browser_mode', sa.String(length=20), server_default='headed_hidden', nullable=False),
    sa.Column('enabled_job_types', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('max_concurrent', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_sessions_user_id'), 'client_sessions', ['user_id'], unique=False)
    op.create_table('credit_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('earn_task', 'spend_job', 'purchase', 'bonus', 'referral', 'refund', 'admin_adjust', 'promotion', name='credit_type'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_created_at'), 'credit_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_credit_transactions_user_id'), 'credit_transactions', ['user_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.Enum('viewlink', 'keyword_seo', 'backlink', 'social_media', name='job_type'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'paused', 'completed', 'cancelled', 'expired', name='job_status'), server_default='draft', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.Text(), nullable=False),
    sa.Column('target_count', sa.Integer(), server_default='100', nullable=False),
    sa.Column('completed_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=True),
    sa.Column('today_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('credit_per_view', sa.Integer(), server_default='1', nullable=False),
    sa.Column('total_credit_budget', sa.Integer(), nullable=True),
    sa.Column('credit_spent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False),
    sa.Column('admin_priority', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_exchange', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('fee', sa.Numeric(precision=12, scale=0), server_default='0', nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=0), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('credit_amount', sa.Integer(), nullable=True),
    sa.Column('tier_id', sa.Integer(), nullable=True),
    sa.Column('tier_duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('payment_ref', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('promotion_id', sa.Integer(), nullable=True),
    sa.Column('bonus_credit', sa.Integer(), server_default='0', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['payment_channels.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['tier_id'], ['membership_tiers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), server_default='string', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('promotion_usage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('promotion_id', 'user_id', 'payment_id', name='uq_promotion_user_payment')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('client_session_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'assigned', 'executing', 'completed', 'failed', 'timeout', name='task_status'), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_retries', sa.Integer(), server_default='2', nullable=False),
    sa.Column('credits_earned', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to'), 'tasks', ['assigned_to'], unique=False)
    op.create_index(op.f('ix_tasks_job_id'), 'tasks', ['job_id'], unique=False)
    op.add_column('users', sa.Column('credit_balance', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_earned', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('total_spent', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('tier_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('referral_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('referred_by', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'users', ['referral_code'])
    op.create_foreign_key(None, 'users', 'users', ['referred_by'], ['id'])
    op.drop_column('users', 'credits')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credits', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'last_login_at')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'referred_by')
    op.drop_column('users', 'referral_code')
    op.drop_column('users', 'tier_expires')
    op.drop_column('users', 'total_spent')
    op.drop_column('users', 'total_earned')
    op.drop_column('users', 'credit_balance')
    op.drop_index(op.f('ix_tasks_job_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_table('promotion_usage')
    op.drop_table('system_settings')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_credit_transactions_user_id'), table_name='credit_transactions')
    op.drop_index(op.f('ix_credit_transactions_created_at'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_index(op.f('ix_client_sessions_user_id'), table_name='client_sessions')
    op.drop_table('client_sessions')
    op.drop_table('proxies')
    op.drop_table('promotions')
    op.drop_table('payment_channels')
    op.drop_table('membership_tiers')
    op.drop_table('credit_packages')
    # ### end Alembic commands ###
